# version: '3.9'

services:

  browserless:
    image: ghcr.io/browserless/chromium
    container_name: browserless
    hostname: browserless
    restart: unless-stopped
    # environment:
    #   - TOKEN=1234
    #   - SCREEN_WIDTH=1920
    #   - SCREEN_HEIGHT=1024
    #   - SCREEN_DEPTH=16
    #   - ENABLE_DEBUGGER=true
    #   - TIMEOUT=600000
    #   - CONCURRENT=15
    ports:
      - 20450:3000  
